export interface ProductStock {
  name: string;
  desc: string;
  id: Number;
  manu: string;
  itemcode: string;
  itemPrice: Number;
  stockCount: Number;
  desginer: string;
  category: string;
  imgPath: string;
  store: string;
}


export const ProductItems = [
  {
    name: "Wishibone Chair",
    desc: "Yチェアとして知られるCH24、ハンス J. ウェグナーがカール・ハンセン＆サン用にデザインし、1950年からずっと生産されている名作です。",
    category: "chair",
    manu: "Carl Hansen & Son",
    itemcode: "CH24",
    itemPrice: 500000,
    stockCount: 10,
    designer: "Hans J. Wegner",
    imgPath: "assets/img/product_img/ch24.png",
    store: "軽井沢店",
  },

  {
    name: "Wishibone Chair Birthday Edition 2022",
    desc: "限定記念モデル CH24 BIRTHDAY CHAIR 2022は、カール・ハンセン & サンが1950年以来絶え間なく生産してきたウェグナーのCH24 (Yチェア) へのオマージュです。",
    category: "chair",
    manu: "Carl Hansen & Son",
    itemcode: "CH24P",
    itemPrice: 1500000,
    stockCount: 5,
    designer: "Hans J. Wegner",
    imgPath: "assets/img/product_img/ch24p.png",
    store: "小諸店",
  },
  {
    name: "Chair",
    desc: "1950年に発表されたハンス J. ウェグナーのダイニングチェア CH23、明快でオーガニックなライン、洗練された斬新なスタイル、クラフトマンシップ溢れるウェグナー初期の名作です。",
    category: "chair",
    manu: "Carl Hansen & Son",
    itemcode: "CH23",
    itemPrice: 900000,
    stockCount: 6,
    designer: "Hans J. Wegner",
    imgPath: "assets/img/product_img/ch23.png",
    store: "佐久店",

  },
  {
    name: "Sawbuck Chair",
    desc: "CH29P ソーバックチェアは、1952年、ハンス J. ウェグナーが、カール・ハンセン＆サンのためにデザイン。木挽きや木工職人に使用されてきた、伝統的な木挽き台がヒントとなったユニークなダイニングチェア。座面の張り加工がより豊かなコンフォートをお約束します。",
    category: "chair",
    manu: "Carl Hansen & Son",
    itemcode: "CH29P",
    itemPrice: 800000,
    stockCount: 8,
    designer: "Hans J. Wegner",
    imgPath: "assets/img/product_img/ch29p.png",
    store:  "松本店", 
  },
  {
    name: "Bar Stool",
    desc: "CH58は、ハンス J. ウェグナーのシンプルで機能的なバースツール、1985年にデザインされました。無垢材、皮革、スチールの組合せが見事に調和したバースツールです。リングは全てステンレススチールになります。",
    category: "chair",
    manu: "Carl Hansen & Son",
    itemcode: "CH58",
    itemPrice: 560000,
    stockCount: 4,
    designer: "Hans J. Wegner",
    imgPath: "assets/img/product_img/ch58.png",
    store: "茅野店",
  },
  {
    name: "Huntsman Chair",
    desc: "ボーエ・モーエンセンが1950年に発表したハンツマンチェア。厳選された素材の持ち味を十二分に引きだすデザイナーの卓越した才能が発揮された逸品、ダイニングチェアとしてはもちろん、ラウンジチェアとしての使用にも適しています。",
    category: "chair",
    manu: "Carl Hansen & Son",
    itemcode: "BM1106",
    itemPrice: 5560000,
    stockCount: 1,
    designer: "Bø`rge Mogensen",
    imgPath: "assets/img/product_img/bm1106.png",
    store: "安曇野店",
  },
  {
    name: "Embrace Chair",
    desc: "エンブレイス・チェアは、2019年EOOSが手掛けるエンブレイス・シリーズにラインアップされたアームレスチェア。軽快で場所を取らず、様々なテーブルと併用することが可能です",
    category: "chair",
    manu: "Carl Hansen & Son",
    itemcode: "E004",
    itemPrice: 660000,
    stockCount: 12,
    designer: "EOOS",
    imgPath: "assets/img/product_img/e004.png",
    store: "立科店",
  },
  {
    name: "Embrace Armchair",
    desc: "エンブレイス・チェアは、カール・ハンセン＆サンとEOOSの協働から生まれた2015年のデザイン。大胆で斬新。機能に優ることはもちろん、あらゆる空間で彫刻的な存在感を放つアームチェアです。",
    category: "chair",
    manu: "Carl Hansen & Son",
    itemcode: "E005",
    itemPrice: 960000,
    stockCount: 12,
    designer: "EOOS",
    imgPath: "assets/img/product_img/e005.png",
    store: "軽井沢店",
  },
  {
    name: "Faaborg Chair",
    desc: "コーア・クリントの代表作、KK9662 フォーボーチェア。1914年にデザインされ、1915年に開館したフォーボー美術館の開館式典で発表されました。完璧と言える素材、フォルムそして機能の融合。発表以来デニッシュモダンの象徴として君臨する名作です。",
    category: "chair",
    manu: "Carl Hansen & Son",
    itemcode: "KK96620",
    itemPrice: 1960000,
    stockCount: 2,
    designer: "Kaare Klint",
    imgPath: "assets/img/product_img/kk99620.png",
    store: "安曇野店", 
  },
  {
    name: "Large Red Armchair",
    desc: "ラージ・レッド チェアのアーム付きバージョンは、コーア・クリントにより、1930年に当時のデンマーク首相だった、トーバル・スタウニングの国会議事堂にある執務室用の椅子としてデザインされました。",
    category: "chair",
    manu: "Carl Hansen & Son",
    itemcode: "KK37581",
    itemPrice: 996000,
    stockCount: 1,
    designer: "Kaare Klint",
    imgPath: "assets/img/product_img/kk37581.png",
    store:  "長野店",
  },
  {
    name: "T-Chair",
    desc: "斬新な彫刻的なフォルムが芸術性を感じさせるT-チェア。クラフトマンシップとコンフォートを突き詰めたデザインです。",
    category: "chair",
    manu: "Carl Hansen & Son",
    itemcode: "OW58",
    itemPrice: 996000,
    stockCount: 9,
    designer: "Ole Wanscher",
    imgPath: "assets/img/product_img/ow58.png",
    store: "茅野店", 
  },
  {
    name: "Oculus Chair",
    desc: "ハンス J. ウェグナーが、1960年にデザインしたCH468　オキュラスチェア。オリジナル図面の発見を機に半世紀を経て市場に紹介されたウェグナーデザインです。 脚はステンレスのみになります。",
    category: "lounge chair",
    manu: "Carl Hansen & Son",
    itemcode: "CH468",
    itemPrice: 2996000,
    stockCount: 8,
    designer: "Hans J. Wegner",
    imgPath: "assets/img/product_img/ch468.png",
    store:  "上田店",
  },
  {
    name: "Lounge Chair",
    desc: "ラウンジチェア CH22は、ハンス J. ウェグナーがカール・ハンセン＆サンに初めてデザインした椅子コレクションの一つ。1950年に発表されたこれらの椅子は、いずれもデニッシュモダンの名作として今日アイコン的な存在となっています。",
    category: "lounge chair",
    manu: "Carl Hansen & Son",
    itemcode: "CH22",
    itemPrice: 1996000,
    stockCount: 6,
    designer: "Hans J. Wegner",
    imgPath: "assets/img/product_img/ch22.png",
    store: "松本店",
  },
  {
    name: "Sofa",
    desc: "ソファ CH103は、ハンス J. ウェグナーによる1970年発表の３人掛けソファ、モダンなインテリに最適なソファです。洗練されたハンドポリッシュ仕上げのステンレススチールと伝統的な皮革の組合せ、そしてコンフォートを追求したフォームと羽毛を用いたクッション。多様な空間に対応する家具シリーズの一つとして1970年に発表されました。",
    category: "sofa",
    manu: "Carl Hansen & Son",
    itemcode: "CH103",
    itemPrice: 5996000,
    stockCount: 5,
    designer: "Hans J. Wegner",
    imgPath: "assets/img/product_img/ch103.png",
    store: "立科店",
  },
  {
    name: "Sofa",
    desc: "ハンス J. ウェグナーのCH162は、構造そのものが美しい意匠となったウェグナーならではの2人掛けソファ。常に機能を追求したウェグナーは、このソファのデザインで構造を露出するという新しい試みに挑戦、結果として素晴らしいソファが出来上がりました。",
    category: "sofa",
    manu: "Carl Hansen & Son",
    itemcode: "CH162",
    itemPrice: 2996000,
    stockCount: 10,
    designer: "Hans J. Wegner",
    imgPath: "assets/img/product_img/ch162.png",
    store: "佐久店", 
  },
  {
    name: "Daybed",
    desc: "1958年、ボーエ・モーエンセンによってデザインされたBM0865デイベッドは、組み合わせることによってより多様に使用できる遊び心に満ちたデザインです。FSC®認証を受けたオークの無垢材を素材として使用し、製造しています（FSC-C135991）。カール・ハンセン＆サンから復刻されました。",
    category: "sofa",
    manu: "Carl Hansen & Son",
    itemcode: "BMO865",
    itemPrice: 2996000,
    stockCount: 4,
    designer: "Børge Mogensen",
    imgPath: "assets/img/product_img/bm0865.png",
    store: "小諸店",
  },
  {
    name: "Coupe Sofa",
    desc: "1936年に発表されたクーペ・ソファ。フリッツ・ヘニングセンの独創性溢れる逸品です。ヘニングセンの個性的な人柄と美しいフォルムを創り出す才能が溢れたソファ。あらゆる空間でその魅力を発揮します。",
    category: "sofa",
    manu: "Carl Hansen & Son",
    itemcode: "FH436",
    itemPrice: 7996000,
    stockCount: 1,
    designer: "Frits Henningsen",
    imgPath: "assets/img/product_img/fh436.png",
    store:  "立科店",
  },
  {
    name: "Colonial Sofa",
    desc: "OW149 コロニアルソファは1964年に発表されました。当時はわずかに生産されたにすぎず、2015年、カール・ハンセン＆サンがコロニアルシリーズの一つとして復刻するまで、その存在はあまり知られていませんでした。",
    category: "sofa",
    manu: "Carl Hansen & Son",
    itemcode: "OW149",
    itemPrice: 996000,
    stockCount: 3,
    designer: "Ole Wanscher",
    imgPath: "assets/img/product_img/ow149.png",
    store: "安曇野店", 
  },
  {
    name: "Daybed",
    desc: "TK8 デイベッドはトーマス・ボー・カストホルムにより、2009年にデザインされました。特徴的なフォルムとスタイリッシュな佇まい。発表と同時に、次世代の古典ともいわれるほど高い評価を受けています。",
    category: "sofa",
    manu: "Carl Hansen & Son",
    itemcode: "TK8",
    itemPrice: 1996000,
    stockCount: 3,
    designer: "Thomas Bo Kastholm",
    imgPath: "assets/img/product_img/tk8.png",
    store: "小諸店",
  },
  {
    name: "Coffee Table",
    desc: "ハンス J. ウェグナーによる、コーヒーテーブル CH108は、ガラスとスチールを組み合わせたシリーズの一つ、大胆なラインと素材の調和が美しいデザインです。ポリッシュしたステンレスの味のある素材感、そして使い勝手のいい大きめのガラス天板。あらゆる空間に適したコーヒーテーブルです。",
    category: "coffee table",
    manu: "Carl Hansen & Son",
    itemcode: "CH108",
    itemPrice: 996000,
    stockCount: 10,
    designer: "Hans J. Wegner",
    imgPath: "assets/img/product_img/ch108.png",
    store: "茅野店", 
  },
  {
    name: "Coffee Table",
    desc: "コーヒーテーブル CH011は、ハンス J. ウェグナーにより、1954年にデザインされた洗練された角形テーブル。モダンな美しさと機能性を巧みに融合させたデザインは、様々な場での使用を可能にしています。",
    category: "coffee table",
    manu: "Carl Hansen & Son",
    itemcode: "CH011",
    itemPrice: 996000,
    stockCount: 2,
    designer: "Hans J. Wegner",
    imgPath: "assets/img/product_img/ch011.png",
    store: "上田店",
  },
]


